##numpy array basic 

In [1]:
import numpy as np
array1 = np.array([[1,3,6,4,5],[2,1,4,5,6]])
array1


array([[1, 3, 6, 4, 5],
       [2, 1, 4, 5, 6]])

In [2]:
array1.shape


(2, 5)

In [3]:
array1.dtype


dtype('int32')

In [4]:
a = np.arange(1,10)
print(a)

[1 2 3 4 5 6 7 8 9]


In [5]:
np.ones(4)

array([1., 1., 1., 1.])

In [6]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
array1

array([[1, 3, 6, 4, 5],
       [2, 1, 4, 5, 6]])

In [8]:
array1*array1

array([[ 1,  9, 36, 16, 25],
       [ 4,  1, 16, 25, 36]])

##Slicing

In [9]:
array2= np.array([1,3,4,5,6])

In [12]:
array2[1:3]

array([3, 4])

In [15]:
import numpy as np

In [27]:
ar3 =np.array([[1,2,3],
       [4,5,6]])

ar3.sum(axis=1)                               #adds the rows


array([ 6, 15])

In [28]:
ar3.sum(axis=0)                                 #adds the columns

array([5, 7, 9])

In [ ]:
b = np.array([[]])